from __future__ import annotations

import argparse
import json
import re
import shutil
import sys
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import yaml

try:
    import tomllib as _toml
except ImportError:  # Python < 3.11
    try:
        import tomli as _toml  # type: ignore[no-redef]
    except ImportError:
        _toml = None

_SCHEMA_URL = "https://opencode.ai/config.json"
_SKILL_NAME_RE = re.compile(r"^[a-z0-9]+(-[a-z0-9]+)*$")

# User-level (global) config root for opencode: ~/.config/opencode
USER_CONFIG_DIR = Path.home() / ".config" / "opencode"

_HERE = Path(__file__).resolve().parent
REPO_ROOT = _HERE.parents[2]
HARNESS_DIR = REPO_ROOT / "harness"
RULES_DIR = HARNESS_DIR / "rules"
AGENTS_SRC_DIR = HARNESS_DIR / "agents"
SKILLS_SRC_DIR = HARNESS_DIR / "skills"
LIFECYCLE_DIR = HARNESS_DIR / "lifecycle"
HOOKS_MANIFEST = LIFECYCLE_DIR / "hooks.toml"
REGISTRY_PATH = HARNESS_DIR / "mcp" / "registry.json"
CONFIG_PATH = REPO_ROOT / "opencode.json"
OPCODE_DIR = REPO_ROOT / ".opencode"
AGENTS_DST_DIR = OPCODE_DIR / "agents"
SKILLS_DST_DIR = OPCODE_DIR / "skills"
PLUGINS_DST_DIR = OPCODE_DIR / "plugins"
PLUGIN_PATH = PLUGINS_DST_DIR / "opc-hooks.ts"
SCHEMA_PATH = _HERE / "schemas" / "opencode-config.json"
MODEL_ID = ""

_TOOL_PERMISSION_MAP = {
    "Read": "read",
    "Grep": "grep",
    "Glob": "glob",
    "Bash": "bash",
    "List": "list",
    "Edit": "edit",
    "Write": "edit",
    "ApplyPatch": "edit",
    "TodoWrite": "todowrite",
    "Task": "task",
    "Agent": "task",
    "WebFetch": "webfetch",
    "WebSearch": "websearch",
}


def _load_hooks() -> dict[str, object]:
    if _toml is None:
        return {}
    if not HOOKS_MANIFEST.exists():
        return {}
    try:
        data = _toml.loads(HOOKS_MANIFEST.read_text(encoding="utf-8-sig"))
    except (_toml.TOMLDecodeError, OSError):
        return {}
    hooks = data.get("hooks")
    return hooks if isinstance(hooks, dict) else {}


_OPENCODE_EVENT_BRIDGE = {
    "session_start": "session.created",
    "pre_tool_use": "tool.execute.before",
    "post_tool_use": "tool.execute.after",
    "pre_compact": "experimental.session.compacting",
    "session_stop": "session.idle",
}

_OPENCODE_TOOL_MATCHER = {
    "Read": "read",
    "Edit": "edit",
    "MultiEdit": "edit",
    "Write": "write",
    "Grep": "grep",
    "Bash": "bash",
    "Task": "task",
    "Glob": "glob",
    "List": "list",
    "TodoWrite": "todowrite",
    "WebFetch": "webfetch",
    "WebSearch": "websearch",
}


def _opencode_matcher(matcher: object) -> list[str]:
    if not isinstance(matcher, str) or not matcher:
        return []
    if matcher == "*":
        return []
    tools: list[str] = []
    for part in matcher.split("|"):
        name = part.strip()
        if not name:
            continue
        mapped = _OPENCODE_TOOL_MATCHER.get(name, name.lower())
        if mapped not in tools:
            tools.append(mapped)
    return tools


def _bridge_handlers() -> dict[str, list[dict[str, object]]]:
    hooks = _load_hooks()
    bridged: dict[str, list[dict[str, object]]] = {}
    for event, handlers in sorted(hooks.items()):
        opencode_event = _OPENCODE_EVENT_BRIDGE.get(event)
        if not opencode_event:
            continue
        values = handlers if isinstance(handlers, list) else [handlers]
        entries: list[dict[str, object]] = []
        for handler in values:
            if not isinstance(handler, dict) or bool(handler.get("disabled")):
                continue
            command = handler.get("command")
            if not isinstance(command, str) or not command:
                continue
            entry: dict[str, object] = {"command": command}
            matchers = _opencode_matcher(handler.get("matcher"))
            if matchers:
                entry["matcher"] = matchers
            timeout = handler.get("timeout")
            if isinstance(timeout, int):
                entry["timeout"] = timeout
            entries.append(entry)
        if entries:
            bridged[opencode_event] = entries
    return bridged


_OPENCODE_PLUGIN = """// Generated by opc/scripts/harness/gen_opencode.py from
// harness/lifecycle/hooks.toml. Do not edit this file; edit the neutral
// manifest and regenerate.

// Bridges the neutral lifecycle hook manifest onto opencode plugin events.
// opencode has no config-level `hooks` key, so hooks surface as this
// auto-loaded plugin (opencode auto-loads every file under .opencode/plugins/).
//
// Event mapping (neutral -> opencode):
//   session_start -> session.created  (routed via the generic `event` hook,
//                                      keyed on event.type; opencode exposes
//                                      no top-level session.created hook key)
//   pre_tool_use  -> tool.execute.before  (tool names lowercased)
//   post_tool_use -> tool.execute.after
//   pre_compact   -> experimental.session.compacting
//   session_stop  -> session.idle  (routed via the `event` hook; fires once
//                                   per session on the first idle event after
//                                   session start, approximating session end
//                                   because `session.idle` itself fires
//                                   per turn)
//   prompt_submit -> unmappable (no clean equivalent; skipped)
//
// Commands spawn via Bun.spawn with NO shell, so `$HOME` is expanded at
// runtime instead of baked in at generation time. Timeouts from the manifest
// are informational here; the detached spawns are fire-and-forget.

import type { Plugin } from "@opencode-ai/plugin";
import os from "node:os";

type OpcHook = {
  command: string;
  matcher?: string[];
  timeout?: number;
};

const HOOKS: Record<string, OpcHook[]> = {
@@HOOKS@@
};

function expandCommand(command: string): string {
  const home = process.env.HOME || os.homedir();
  return command.replace(/\\$HOME/g, home);
}

function spawnHook(hook: OpcHook, env: Record<string, string>, cwd: string): void {
  try {
    const args = expandCommand(hook.command).split(/\\s+/);
    Bun.spawn(args, { env, cwd, stdout: "ignore", stderr: "ignore" });
  } catch {
    // The harness never fails a session because of a hook.
  }
}

export const OpcHooksPlugin: Plugin = async ({ directory, project }) => {
  const cwd = directory ?? project?.path ?? process.cwd();
  const baseEnv = (event: string, input: any): Record<string, string> => {
    const sessionID =
      input?.sessionID ?? input?.session?.id ?? process.env.OPC_SESSION_ID ?? "";
    return {
      OPC_PROJECT_DIR: cwd,
      OPC_SESSION_ID: sessionID,
      OPC_EVENT: event,
      OPC_TOOL: input?.tool ?? "",
    };
  };
  const sessionEndFired: Record<string, boolean> = {};
  return {
    // opencode exposes no top-level `session.created`/`session.idle` hook
    // keys, so session lifecycle events are routed here via the generic
    // `event` hook and dispatched on event.type.
    event: async ({ event }) => {
      const ev = event as any;
      const type = ev?.type ?? "";
      const sessionID =
        ev?.properties?.sessionID ??
        ev?.properties?.info?.id ??
        process.env.OPC_SESSION_ID ??
        "";
      if (type === "session.created") {
        for (const hook of HOOKS["session.created"] ?? []) {
          spawnHook(hook, baseEnv("session.created", { sessionID }), cwd);
        }
      }
      if (type === "session.idle" && !sessionEndFired[sessionID]) {
        sessionEndFired[sessionID] = true;
        for (const hook of HOOKS["session.idle"] ?? []) {
          spawnHook(hook, baseEnv("session.idle", { sessionID }), cwd);
        }
      }
    },
    "tool.execute.before": async (input) => {
      const tool = String(input?.tool ?? "").toLowerCase();
      const env = baseEnv("tool.execute.before", input);
      env.OPC_TOOL = tool;
      for (const hook of HOOKS["tool.execute.before"] ?? []) {
        if (hook.matcher && hook.matcher.length && !hook.matcher.includes(tool)) continue;
        spawnHook(hook, env, cwd);
      }
    },
    "tool.execute.after": async (input) => {
      const tool = String(input?.tool ?? "").toLowerCase();
      const env = baseEnv("tool.execute.after", input);
      env.OPC_TOOL = tool;
      for (const hook of HOOKS["tool.execute.after"] ?? []) {
        if (hook.matcher && hook.matcher.length && !hook.matcher.includes(tool)) continue;
        spawnHook(hook, env, cwd);
      }
    },
    "experimental.session.compacting": async (input) => {
      for (const hook of HOOKS["experimental.session.compacting"] ?? []) {
        spawnHook(hook, baseEnv("experimental.session.compacting", input), cwd);
      }
    },
  };
};
"""


def _emit_opencode_plugin() -> str:
    bridged = _bridge_handlers()
    entries = []
    for opencode_event in (
        "session.created",
        "tool.execute.before",
        "tool.execute.after",
        "experimental.session.compacting",
        "session.idle",
    ):
        hooks = bridged.get(opencode_event)
        if not hooks:
            continue
        body = ",\n    ".join(json.dumps(hook, ensure_ascii=False) for hook in hooks)
        entries.append(f'  "{opencode_event}": [\n    {body}\n  ]')
    return _OPENCODE_PLUGIN.replace("@@HOOKS@@", ",\n".join(entries))


def _parse_frontmatter(text: str) -> Tuple[dict, str]:
    if not text.startswith("---"):
        return {}, text
    parts = text.split("---", 2)
    if len(parts) < 3:
        return {}, text
    try:
        data = yaml.safe_load(parts[1]) or {}
    except yaml.YAMLError:
        data = {}
    if not isinstance(data, dict):
        data = {}
    return data, parts[2].lstrip("\n")


def _permission_from_tools(tools: object) -> Optional[Dict[str, str]]:
    if not isinstance(tools, list):
        return None
    allowed = sorted(
        {
            _TOOL_PERMISSION_MAP[name]
            for name in tools
            if isinstance(name, str) and name in _TOOL_PERMISSION_MAP
        }
    )
    if not allowed:
        return None
    return {**{"*": "deny"}, **{tool: "allow" for tool in allowed}}


def _load_registry() -> dict:
    if not REGISTRY_PATH.exists():
        return {}
    try:
        data = json.loads(REGISTRY_PATH.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return {}
    return data if isinstance(data, dict) else {}


def _translate_server(cfg: object) -> Optional[Dict[str, object]]:
    if not isinstance(cfg, dict):
        return None
    enabled = not bool(cfg.get("disabled"))
    kind = cfg.get("type", "stdio")
    if kind == "http":
        url = cfg.get("url")
        if not isinstance(url, str) or not url:
            return None
        entry: Dict[str, object] = {
            "type": "remote",
            "url": _opencode_expand(url),
            "enabled": enabled,
        }
        headers = cfg.get("headers")
        if isinstance(headers, dict):
            entry["headers"] = {
                str(k): _opencode_expand(str(v)) for k, v in headers.items()
            }
        return entry
    command = cfg.get("command")
    args = cfg.get("args")
    if not isinstance(command, str) or not command:
        return None
    exec_args = [_opencode_expand(command)] + (
        [_opencode_expand(str(x)) for x in args] if isinstance(args, list) else []
    )
    entry = {
        "type": "local",
        "command": exec_args,
        "enabled": enabled,
    }
    env = cfg.get("env")
    if isinstance(env, dict):
        entry["environment"] = {
            str(k): _opencode_expand(str(v)) for k, v in env.items()
        }
    return entry


def _opencode_expand(value: str) -> str:
    """Rewrite $HOME and ${VAR} so opencode can interpret them at runtime.

    opencode's MCP config only substitutes the {env:VAR} / {file:path} forms;
    a literal $HOME is passed to the process untouched, and ${VAR} is never
    expanded. Standardize both at generation time.
    """
    value = value.replace("$HOME", str(Path.home()))
    return re.sub(r"\$\{([A-Za-z_][A-Za-z0-9_]*)\}", r"{env:\1}", value)


def _mcp_config() -> Dict[str, object]:
    registry = _load_registry()
    servers = registry.get("mcpServers", {})
    out: Dict[str, object] = {}
    if not isinstance(servers, dict):
        return out
    for name, cfg in sorted(servers.items()):
        entry = _translate_server(cfg)
        if entry is not None:
            out[name] = entry
    return out


def _instructions() -> List[str]:
    return [f"harness/rules/{path.name}" for path in sorted(RULES_DIR.glob("*.md"))]


def _config() -> Dict[str, object]:
    cfg: Dict[str, object] = {"$schema": "https://opencode.ai/config.json"}
    instructions = _instructions()
    if instructions:
        cfg["instructions"] = instructions
    mcp = _mcp_config()
    if mcp:
        cfg["mcp"] = mcp
    if MODEL_ID:
        cfg["model"] = MODEL_ID
    return cfg


def _emit_agents() -> List[str]:
    AGENTS_DST_DIR.mkdir(parents=True, exist_ok=True)
    emitted: List[str] = []
    for path in sorted(AGENTS_SRC_DIR.glob("*.md")):
        data, body = _parse_frontmatter(path.read_text(encoding="utf-8"))
        name = data.get("name")
        description = data.get("description")
        if not isinstance(name, str) or not isinstance(description, str) or not body:
            continue
        frontmatter: Dict[str, object] = {"description": description, "mode": "subagent"}
        permission = _permission_from_tools(data.get("tools"))
        if permission is not None:
            frontmatter["permission"] = permission
        header = yaml.safe_dump(frontmatter, sort_keys=False, allow_unicode=True).strip()
        (AGENTS_DST_DIR / f"{name}.md").write_text(
            f"---\n{header}\n---\n\n{body}", encoding="utf-8"
        )
        emitted.append(name)
    return emitted


def _emit_skills() -> Tuple[List[str], List[str]]:
    SKILLS_DST_DIR.mkdir(parents=True, exist_ok=True)
    copied: List[str] = []
    skipped: List[str] = []
    seen = set()
    for skill_dir in sorted(SKILLS_SRC_DIR.iterdir()):
        if not skill_dir.is_dir():
            continue
        md = skill_dir / "SKILL.md"
        if not md.exists():
            continue
        data, _ = _parse_frontmatter(md.read_text(encoding="utf-8"))
        name = data.get("name")
        if not (isinstance(name, str) and _SKILL_NAME_RE.match(name)):
            skipped.append(f"{skill_dir.name} (invalid name {name!r})")
            continue
        if name in seen:
            skipped.append(f"{skill_dir.name} (duplicate name {name!r})")
            continue
        seen.add(name)
        dst = SKILLS_DST_DIR / name
        if dst.exists():
            shutil.rmtree(dst)
        shutil.copytree(
            skill_dir,
            dst,
            ignore=shutil.ignore_patterns("*.v6.md", "*.bak", "*.backup"),
        )
        copied.append(name)
    for stale_dir in SKILLS_DST_DIR.iterdir():
        if stale_dir.is_dir() and stale_dir.name not in seen:
            shutil.rmtree(stale_dir)
            print(f"pruned stale skill dir {SKILLS_DST_DIR.name}/{stale_dir.name}")
    return copied, skipped


def _validate(cfg: Dict[str, object]) -> int:
    if not SCHEMA_PATH.exists():
        print(f"schema not cached at {SCHEMA_PATH}; fetch from {_SCHEMA_URL} to enable validation")
        return 0
    try:
        import jsonschema
    except ImportError:
        print("jsonschema not installed; skipping config validation")
        return 0
    schema = json.loads(SCHEMA_PATH.read_text(encoding="utf-8"))
    try:
        jsonschema.validate(cfg, schema)
    except jsonschema.ValidationError as exc:
        location = "/".join(str(part) for part in exc.absolute_path) or "$"
        print(f"config validation failed at {location}: {exc.message}")
        return 1
    except jsonschema.SchemaError as exc:
        print(f"schema error: {exc.message}")
        return 1
    print("config validates against the opencode schema")
    return 0


def main(argv: Optional[List[str]] = None) -> int:
    parser = argparse.ArgumentParser(
        prog="python -m scripts.harness.gen_opencode",
        description=(
            "Generate the OpenCode integration config from the canonical harness tree "
            "(project scope by default, or --user-level for the global config root)"
        ),
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="print the opencode.json that would be written",
    )
    parser.add_argument(
        "--user-level",
        action="store_true",
        help="emit to the user-global root (~/.config/opencode) instead of the project",
    )
    parser.add_argument(
        "--model",
        default="",
        help="pin a model id (top-level \"model\" field in opencode.json)",
    )
    args = parser.parse_args(argv)
    if args.user_level:
        _repoint(USER_CONFIG_DIR)
    globals().update({"MODEL_ID": args.model})
    cfg = _config()
    plugin_text = _emit_opencode_plugin()
    if args.dry_run:
        print(json.dumps(cfg, indent=2, ensure_ascii=False))
        print("--- .opencode/plugins/opc-hooks.ts ---")
        print(plugin_text)
        return 0
    CONFIG_PATH.parent.mkdir(parents=True, exist_ok=True)
    CONFIG_PATH.write_text(json.dumps(cfg, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    PLUGINS_DST_DIR.mkdir(parents=True, exist_ok=True)
    PLUGIN_PATH.write_text(plugin_text, encoding="utf-8")
    agents = _emit_agents()
    copied, skipped = _emit_skills()
    print(
        "wrote "
        f"{CONFIG_PATH.name} with {len(cfg.get('mcp', {}))} mcp servers "
        f"and {len(cfg.get('instructions', []))} rules"
    )
    if MODEL_ID:
        print(f"  model={MODEL_ID}")
    print(f"wrote {PLUGIN_PATH.relative_to(REPO_ROOT)} (opencode hook bridge)")
    print(f"emitted {len(agents)} agents to {AGENTS_DST_DIR.relative_to(REPO_ROOT)}")
    skipped_str = ", ".join(skipped)
    print(
        "copied "
        f"{len(copied)} skills to {SKILLS_DST_DIR.relative_to(REPO_ROOT)}; "
        f"skipped {len(skipped)}: {skipped_str}"
    )
    return _validate(cfg)


def _repoint(root: Path) -> None:
    """Rebind the destination constants to a non-project config root."""
    globals().update(
        {
            "REPO_ROOT": root,
            "CONFIG_PATH": root / "opencode.json",
            "OPCODE_DIR": root,
            "AGENTS_DST_DIR": root / "agents",
            "SKILLS_DST_DIR": root / "skills",
            "PLUGINS_DST_DIR": root / "plugins",
            "PLUGIN_PATH": root / "plugins" / "opc-hooks.ts",
        }
    )


if __name__ == "__main__":
    sys.exit(main())
