from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import sys
from pathlib import Path

try:
    import tomllib as _toml
except ImportError:  # Python < 3.11
    try:
        import tomli as _toml  # type: ignore[no-redef]
    except ImportError:
        _toml = None

_HERE = Path(__file__).resolve().parent
REPO_ROOT = _HERE.parents[2]
HARNESS_DIR = REPO_ROOT / "harness"
RULES_DIR = HARNESS_DIR / "rules"
AGENTS_SRC_DIR = HARNESS_DIR / "agents"
LIFECYCLE_DIR = HARNESS_DIR / "lifecycle"
HOOKS_MANIFEST = LIFECYCLE_DIR / "hooks.toml"
REGISTRY_PATH = HARNESS_DIR / "mcp" / "registry.json"
CLINERULES_DIR = REPO_ROOT / ".clinerules"
CLINE_HOOKS_DIR = CLINERULES_DIR / "hooks"
MCP_JSON_PATH = REPO_ROOT / "cline_mcp_settings.json"

# User-level (global) config roots for Cline
USER_CLINE_DIR = Path.home() / ".cline"
USER_RULES_DIR = Path.home() / ".clinerules"
# Cline CLI/SDK resolves the user MCP settings via resolveMcpSettingsPath():
#   $CLINE_MCP_SETTINGS_PATH if set, else <CLINE_DATA_DIR|~/.cline>/data/settings/cline_mcp_settings.json
# (the docs' `~/.cline/mcp.json` path is NOT read by the CLI - cline/cline#11671, #7249)
USER_MCP_PATH = Path(
    os.environ.get(
        "CLINE_MCP_SETTINGS_PATH",
        str(Path(os.environ.get("CLINE_DATA_DIR", str(USER_CLINE_DIR))) / "data" / "settings" / "cline_mcp_settings.json"),
    )
)
USER_SKILLS_DIR = USER_CLINE_DIR / "skills"
_SKILL_NAME_RE = re.compile(r"^[a-z0-9]+(-[a-z0-9]+)*$")

_LAUNCHER_NAME_RE = re.compile(r"hook_launcher\.py\s+([\w-]+)\s*$")

# Neutral event -> Cline hook type. Cline (v3.36+) hooks are REAL executable
# scripts (JSON in on stdin, JSON out), not model-executed markdown.
_CLINE_EVENT_MAP = {
    "session_start": "TaskStart",
    "prompt_submit": "UserPromptSubmit",
    "pre_tool_use": "PreToolUse",
    "post_tool_use": "PostToolUse",
    "pre_compact": "PreCompact",
    "stop": "TaskComplete",
}

_CLINE_README = """# Cline lifecycle hooks (generated)

Generated by `opc/scripts/harness/gen_cline.py` from the neutral manifest
`harness/lifecycle/hooks.toml`. Experimental.

Cline hooks are real executable scripts (since v3.36): each hook reads one JSON
object on stdin and returns JSON controlling the session (`cancel`,
`contextModification`). These files forward the Cline stdin payload straight
into the neutral python hooks in `harness/lifecycle/hooks/`; the shared
payload adapter (`_payload.py`) understands the Cline field naming.

## Naming (platform-specific)

- Windows: `HookType.ps1` is the only supported form. Hook discovery ignores
  any other name; on Windows hooks run whenever the file exists (no toggle).
- macOS/Linux: extensionless executable named exactly `HookType`. Rename these
  files and `chmod +x`. Enable/disable each hook in the Cline UI (Hooks tab).

## Coverage

| Hook file        | Neutral events forwarded                    |
| ---------------- | ------------------------------------------- |
"""


def _ps1_template(hook_type: str, hook_names: list[str]) -> str:
    names = ",\n  ".join(f'"{name}"' for name in hook_names)
    return (
        "# Generated by opc/scripts/harness/gen_cline.py from\n"
        "# harness/lifecycle/hooks.toml. Experimental. Cline Windows naming: HookType.ps1\n"
        "# (macOS/Linux: extensionless + chmod +x). Forwards the Cline stdin JSON into\n"
        "# the payload adapter, which understands the Cline field naming.\n"
        "$hooks = @(\n"
        f"  {names}\n"
        ")\n"
        "$payload = [Console]::In.ReadToEnd()\n"
        "$env:OPC_PROJECT_DIR = (Get-Location).Path\n"
        f'$env:OPC_EVENT = "{hook_type}"\n'
        "foreach ($hook in $hooks) {\n"
        '  $null = $payload | & uv run "$HOME\\.opc\\hooks\\hook_launcher.py" $hook 2>$null\n'
        "}\n"
        "# Cline expects response JSON; the neutral hooks are advisory, so respond permissively.\n"
        "Write-Output '{\"cancel\":false,\"contextModification\":\"\"}'\n"
    )


def _load_hooks() -> dict:
    if _toml is None or not HOOKS_MANIFEST.exists():
        return {}
    try:
        data = _toml.loads(HOOKS_MANIFEST.read_text(encoding="utf-8-sig"))
    except (_toml.TOMLDecodeError, OSError):
        return {}
    hooks = data.get("hooks")
    return hooks if isinstance(hooks, dict) else {}


def _python_hook_names() -> dict[str, list[str]]:
    """Map each Cline hook type to the neutral python-launcher hook names."""
    mapped: dict[str, list[str]] = {hook_type: [] for hook_type in _CLINE_EVENT_MAP.values()}
    for event, handlers in _load_hooks().items():
        cline_type = _CLINE_EVENT_MAP.get(event)
        if not cline_type:
            continue
        values = handlers if isinstance(handlers, list) else [handlers]
        for handler in values:
            if not isinstance(handler, dict) or bool(handler.get("disabled")):
                continue
            command = handler.get("command")
            if not isinstance(command, str):
                continue
            match = _LAUNCHER_NAME_RE.search(command)
            if match:
                name = match.group(1)
                if name not in mapped[cline_type]:
                    mapped[cline_type].append(name)
    return mapped


def _emit_hooks() -> list[str]:
    CLINE_HOOKS_DIR.mkdir(parents=True, exist_ok=True)
    mapped = _python_hook_names()
    emitted: list[str] = []
    for cline_type, hook_names in sorted(mapped.items()):
        if not hook_names:
            continue
        target = CLINE_HOOKS_DIR / f"{cline_type}.ps1"
        target.write_text(_ps1_template(cline_type, hook_names), encoding="utf-8")
        emitted.append(target.name)
    readme = _CLINE_README
    for cline_type, hook_names in sorted(mapped.items()):
        if hook_names:
            readme += f"| `{cline_type}.ps1` | {', '.join(hook_names)} |\n"
    readme += (
        "\n## Caveats\n\n"
        "- Cline hook files filter by UI toggle, not by per-tool matcher. A manifest `matcher`\n"
        "  (e.g. `Edit|Write`) is therefore NOT enforced by Cline's PreToolUse/PostToolUse hooks;\n"
        "  the forwarded hook must tolerate every tool (they do, via `_payload.py`).\n"
        "- `contextModification` output from Cline hooks is currently passed through verbatim as\n"
        "  `cancel:false` (the neutral hooks are advisory). Wire structured output in Step 8.\n"
        "- Hooks resolve `~/.opc/hooks/hook_launcher.py`; create the `~/.opc/hooks` junction, or\n"
        "  set `OPC_PROJECT_DIR` and rely on the launcher's canonical-directory search.\n"
    )
    (CLINE_HOOKS_DIR / "README.md").write_text(readme, encoding="utf-8")
    return emitted


def _load_registry() -> dict:
    if not REGISTRY_PATH.exists():
        return {}
    try:
        data = json.loads(REGISTRY_PATH.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return {}
    return data if isinstance(data, dict) else {}


def _translate_server(cfg: object) -> dict[str, object] | None:
    if not isinstance(cfg, dict):
        return None
    disabled = bool(cfg.get("disabled"))
    kind = cfg.get("type", "stdio")
    if kind == "http":
        url = cfg.get("url")
        if not isinstance(url, str) or not url:
            return None
        entry: dict[str, object] = {
            "type": "streamableHttp",
            "url": url,
            "disabled": disabled,
            "autoApprove": [],
        }
        headers = cfg.get("headers")
        if isinstance(headers, dict):
            entry["headers"] = {str(k): str(v) for k, v in headers.items()}
        return entry
    command = cfg.get("command")
    if not isinstance(command, str) or not command:
        return None
    entry: dict[str, object] = {
        "command": command,
        "disabled": disabled,
        "autoApprove": [],
    }
    args = cfg.get("args")
    if isinstance(args, list) and args:
        entry["args"] = [str(x) for x in args]
    env = cfg.get("env")
    if isinstance(env, dict):
        entry["env"] = {str(k): str(v) for k, v in env.items()}
    return entry


def _mcp_config() -> dict[str, object]:
    out: dict[str, object] = {}
    servers: dict[str, object] = {}
    registry = _load_registry()
    raw = registry.get("mcpServers", {})
    if isinstance(raw, dict):
        for name, server in sorted(raw.items()):
            entry = _translate_server(server)
            if entry is not None:
                servers[name] = entry
    if servers:
        out["mcpServers"] = servers
    return out


def _emit_rules() -> list[str]:
    CLINERULES_DIR.mkdir(parents=True, exist_ok=True)
    emitted: list[str] = []
    for path in sorted(RULES_DIR.glob("*.md")):
        name = path.name
        (CLINERULES_DIR / name).write_text(path.read_text(encoding="utf-8"), encoding="utf-8")
        emitted.append(name)
    return emitted


def _validate(mcp_text: str) -> int:
    try:
        parsed = json.loads(mcp_text)
    except json.JSONDecodeError as exc:
        print(f"generated cline_mcp_settings.json is not valid JSON: {exc}")
        return 1
    servers = parsed.get("mcpServers", {})
    if isinstance(servers, dict):
        for name, entry in servers.items():
            if not isinstance(entry, dict):
                continue
            if not (entry.get("command") or entry.get("url")):
                print(f"mcpServers.{name} is malformed: {entry!r}")
                return 1
    print(
        f"cline_mcp_settings.json parses; mcpServers={len(servers)} "
        f"rules={len(list(CLINERULES_DIR.glob('*.md'))) if CLINERULES_DIR.is_dir() else 0} "
        f"agents={len(list(AGENTS_SRC_DIR.glob('*.md')))}"
    )
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="python -m scripts.harness.gen_cline",
        description=(
            "Generate the Cline integration config from the canonical harness tree "
            "(project scope by default, or --user-level for the global ~/.cline root)"
        ),
    )
    parser.add_argument(
        "--dry-run", action="store_true", help="print the generated files without writing"
    )
    parser.add_argument(
        "--user-level",
        action="store_true",
        help="emit rules/skills/MCP to the user-global roots (~/.clinerules, ~/.cline) instead of the project",
    )
    parser.add_argument(
        "--model",
        default="",
        help="accepted for uniform generator CLI; model pinning is n/a for Cline config files",
    )
    args = parser.parse_args(argv)
    if args.model:
        print("note: model pinning n/a for Cline config files (set provider/model in the Cline UI or ~/.cline/data/settings/providers.json)")
    cfg = _mcp_config()
    mcp_text = json.dumps(cfg, indent=2, ensure_ascii=False) + "\n"
    if args.dry_run:
        print(mcp_text)
        print("--- .clinerules/ ---")
        for path in sorted(RULES_DIR.glob("*.md")):
            print(path.name)
        print("--- .clinerules/hooks/ ---")
        mapped = _python_hook_names()
        for cline_type, hook_names in sorted(mapped.items()):
            if hook_names:
                print(f"  {cline_type}.ps1 -> {', '.join(hook_names)}")
        return 0
    rules = _emit_rules() if not args.user_level else []
    hooks = _emit_hooks() if not args.user_level else []
    if args.user_level:
        print("(project-level Cline files skipped: --user-level selected)")
    else:
        MCP_JSON_PATH.write_text(mcp_text, encoding="utf-8")
        print(f"wrote {MCP_JSON_PATH.relative_to(REPO_ROOT)}")
        print(f"wrote {len(rules)} rules to {CLINERULES_DIR.relative_to(REPO_ROOT)}")
        print(
            f"wrote {len(hooks)} Cline hook scripts + README to "
            f"{CLINE_HOOKS_DIR.relative_to(REPO_ROOT)}"
        )
    if args.user_level:
        _emit_user_level(cfg)
    return _validate(mcp_text)


def _emit_user_level(generated_mcp: dict[str, object]) -> None:
    """Emit the user-global Cline integration: rules, MCP merge, and skills."""
    imported_rules = _emit_user_rules()
    if imported_rules:
        print(f"imported {len(imported_rules)} rules to {USER_RULES_DIR}")
    merged = _merge_user_mcp(generated_mcp)
    USER_MCP_PATH.parent.mkdir(parents=True, exist_ok=True)
    USER_MCP_PATH.write_text(
        json.dumps(merged, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )
    print(f"merged {len(merged.get('mcpServers', {}))} mcp servers into {USER_MCP_PATH}")
    copied, skipped = _copy_user_skills()
    if copied:
        print(f"copied {len(copied)} skills to {USER_SKILLS_DIR}")
    if skipped:
        print(f"skipped skills: {', '.join(skipped)}")
    print(
        "(user-level Cline hooks not emitted: global hooks are platform-specific and"
        " UI-toggled in Cline; see ~/Documents/Cline/Hooks on Windows/macOS)"
    )


def _emit_user_rules() -> list[str]:
    USER_RULES_DIR.mkdir(parents=True, exist_ok=True)
    imported: list[str] = []
    for path in sorted(RULES_DIR.glob("*.md")):
        (USER_RULES_DIR / path.name).write_text(
            path.read_text(encoding="utf-8"), encoding="utf-8"
        )
        imported.append(path.name)
    return imported


def _merge_user_mcp(generated: dict[str, object]) -> dict[str, object]:
    """Merge generated mcpServers into the user's global Cline settings, preserving
    any existing user-defined servers while letting generated entries win on update."""
    existing: dict[str, object] = {}
    if USER_MCP_PATH.exists():
        try:
            parsed = json.loads(USER_MCP_PATH.read_text(encoding="utf-8"))
            if isinstance(parsed, dict):
                existing = parsed
        except json.JSONDecodeError:
            print(f"warning: {USER_MCP_PATH} is not valid JSON; starting fresh")
    gen_servers = generated.get("mcpServers", {})
    merged_servers = dict(existing.get("mcpServers", {}))
    if isinstance(gen_servers, dict):
        merged_servers.update(gen_servers)
    out = dict(existing)
    out["mcpServers"] = merged_servers
    return out


def _copy_user_skills() -> tuple[list[str], list[str]]:
    """Copy canonical skills into the user-global Cline skills directory.

    Skill names come from the directory slug (harness/skills keeps slugs equal to
    frontmatter `name`), which is what Cline keys its skills dir on.
    """
    copied: list[str] = []
    skipped: list[str] = []
    seen: set[str] = set()
    for skill_dir in sorted((HARNESS_DIR / "skills").iterdir()):
        if not skill_dir.is_dir():
            continue
        if not (skill_dir / "SKILL.md").exists():
            continue
        name = skill_dir.name
        if not _SKILL_NAME_RE.match(name):
            skipped.append(f"{name} (invalid slug)")
            continue
        if name in seen:
            skipped.append(f"{name} (duplicate)")
            continue
        seen.add(name)
        dst = USER_SKILLS_DIR / name
        if dst.exists():
            shutil.rmtree(dst)
        shutil.copytree(
            skill_dir,
            dst,
            ignore=shutil.ignore_patterns("*.v6.md", "*.bak", "*.backup"),
        )
        copied.append(name)
    USER_SKILLS_DIR.mkdir(parents=True, exist_ok=True)
    for stale_dir in USER_SKILLS_DIR.iterdir():
        if stale_dir.is_dir() and stale_dir.name not in seen:
            shutil.rmtree(stale_dir)
            print(f"pruned stale skill dir {USER_SKILLS_DIR.name}/{stale_dir.name}")
    return copied, skipped


if __name__ == "__main__":
    sys.exit(main())
