# Generated by opc/scripts/harness/gen_cline.py from
# harness/lifecycle/hooks.toml. Experimental. Cline Windows naming: HookType.ps1
# (macOS/Linux: extensionless + chmod +x). Forwards the Cline stdin JSON into
# the payload adapter, which understands the Cline field naming.
$hooks = @(
  "persist-project-dir",
  "braintrust-session-start",
  "session-register",
  "session-symbol-index",
  "session-start-continuity"
)
$payload = [Console]::In.ReadToEnd()
$env:OPC_PROJECT_DIR = (Get-Location).Path
$env:OPC_EVENT = "TaskStart"
foreach ($hook in $hooks) {
  $null = $payload | & uv run "$HOME\.opc\hooks\hook_launcher.py" $hook 2>$null
}
# Cline expects response JSON; the neutral hooks are advisory, so respond permissively.
Write-Output '{"cancel":false,"contextModification":""}'
