// Generated by opc/scripts/harness/gen_opencode.py from
// harness/lifecycle/hooks.toml. Do not edit this file; edit the neutral
// manifest and regenerate.

// Bridges the neutral lifecycle hook manifest onto opencode plugin events.
// opencode has no config-level `hooks` key, so hooks surface as this
// auto-loaded plugin (opencode auto-loads every file under .opencode/plugins/).
//
// Event mapping (neutral -> opencode):
//   session_start -> session.created
//   pre_tool_use  -> tool.execute.before  (tool names lowercased)
//   post_tool_use -> tool.execute.after
//   pre_compact   -> experimental.session.compacting
//   session_stop  -> session.idle  (approximation: opencode has NO
//                                   session.closed/stop event)
//   prompt_submit -> unmappable (no clean equivalent; skipped)
//
// Commands spawn via Bun.spawn with NO shell, so `$HOME` is expanded at
// runtime instead of baked in at generation time. Timeouts from the manifest
// are informational here; the detached spawns are fire-and-forget.

import type { Plugin } from "@opencode-ai/plugin";
import os from "node:os";

type OpcHook = {
  command: string;
  matcher?: string[];
  timeout?: number;
};

const HOOKS: Record<string, OpcHook[]> = {
  "session.created": [
    {"command": "uv run $HOME/.opc/hooks/hook_launcher.py persist-project-dir"},
    {"command": "uv run $HOME/.opc/hooks/hook_launcher.py braintrust-session-start"},
    {"command": "node $HOME/.claude/hooks/dist/session-register.mjs", "timeout": 10},
    {"command": "uv run $HOME/.opc/hooks/hook_launcher.py session-symbol-index", "timeout": 5},
    {"command": "uv run $HOME/.opc/hooks/hook_launcher.py session-start-continuity", "matcher": ["resume", "compact", "clear"]},
    {"command": "node $HOME/.claude/hooks/dist/session-start-tldr-cache.mjs", "matcher": ["startup", "resume"], "timeout": 2}
  ],
  "tool.execute.before": [
    {"command": "uv run $HOME/.opc/hooks/hook_launcher.py pre-tool-use-broadcast"},
    {"command": "uv run $HOME/.opc/hooks/hook_launcher.py path-rules", "matcher": ["read", "edit", "write"], "timeout": 5},
    {"command": "node $HOME/.claude/hooks/dist/tldr-read-enforcer.mjs", "matcher": ["read"], "timeout": 20},
    {"command": "node $HOME/.claude/hooks/dist/smart-search-router.mjs", "matcher": ["grep"], "timeout": 10},
    {"command": "node $HOME/.claude/hooks/dist/tldr-context-inject.mjs", "matcher": ["task"], "timeout": 30},
    {"command": "node $HOME/.claude/hooks/dist/arch-context-inject.mjs", "matcher": ["task"], "timeout": 30},
    {"command": "node $HOME/.claude/hooks/dist/file-claims.mjs", "matcher": ["edit"], "timeout": 5},
    {"command": "node $HOME/.claude/hooks/dist/edit-context-inject.mjs", "matcher": ["edit"], "timeout": 5},
    {"command": "node $HOME/.claude/hooks/dist/signature-helper.mjs", "matcher": ["edit"], "timeout": 5}
  ],
  "tool.execute.after": [
    {"command": "uv run $HOME/.opc/hooks/hook_launcher.py typescript-preflight", "matcher": ["edit", "write"], "timeout": 40},
    {"command": "node $HOME/.claude/hooks/dist/compiler-in-the-loop.mjs", "matcher": ["edit", "write"], "timeout": 30},
    {"command": "node $HOME/.claude/hooks/dist/post-edit-notify.mjs", "matcher": ["edit", "write"], "timeout": 5},
    {"command": "node $HOME/.claude/hooks/dist/post-edit-diagnostics.mjs", "matcher": ["edit", "write"], "timeout": 10},
    {"command": "node $HOME/.claude/hooks/dist/handoff-index.mjs", "matcher": ["write"]},
    {"command": "uv run $HOME/.opc/hooks/hook_launcher.py post-tool-use-tracker", "matcher": ["edit", "write", "bash"], "timeout": 120},
    {"command": "uv run $HOME/.opc/hooks/hook_launcher.py braintrust-post-tool-use"},
    {"command": "node $HOME/.claude/hooks/dist/import-validator.mjs", "matcher": ["edit", "write"], "timeout": 5},
    {"command": "node $HOME/.claude/hooks/dist/import-error-detector.mjs", "matcher": ["bash"], "timeout": 5}
  ],
  "experimental.session.compacting": [
    {"command": "uv run $HOME/.opc/hooks/hook_launcher.py pre-compact-continuity"}
  ],
  "session.idle": [
    {"command": "uv run $HOME/.opc/hooks/hook_launcher.py session-end-cleanup"},
    {"command": "uv run $HOME/.opc/hooks/hook_launcher.py session-outcome"},
    {"command": "uv run $HOME/.opc/hooks/hook_launcher.py braintrust-session-end"}
  ]
};

function expandCommand(command: string): string {
  const home = process.env.HOME || os.homedir();
  return command.replace(/\$HOME/g, home);
}

function spawnHook(hook: OpcHook, env: Record<string, string>, cwd: string): void {
  try {
    const args = expandCommand(hook.command).split(/\s+/);
    Bun.spawn(args, { env, cwd, stdout: "ignore", stderr: "ignore" });
  } catch {
    // The harness never fails a session because of a hook.
  }
}

export const OpcHooksPlugin: Plugin = async ({ directory, project }) => {
  const cwd = directory ?? project?.path ?? process.cwd();
  const baseEnv = (event: string, input: any): Record<string, string> => {
    const sessionID =
      input?.sessionID ?? input?.session?.id ?? process.env.OPC_SESSION_ID ?? "";
    return {
      OPC_PROJECT_DIR: cwd,
      OPC_SESSION_ID: sessionID,
      OPC_EVENT: event,
      OPC_TOOL: input?.tool ?? "",
    };
  };
  return {
    "session.created": async (input) => {
      for (const hook of HOOKS["session.created"] ?? []) {
        spawnHook(hook, baseEnv("session.created", input), cwd);
      }
    },
    "tool.execute.before": async (input) => {
      const tool = String(input?.tool ?? "").toLowerCase();
      const env = baseEnv("tool.execute.before", input);
      env.OPC_TOOL = tool;
      for (const hook of HOOKS["tool.execute.before"] ?? []) {
        if (hook.matcher && hook.matcher.length && !hook.matcher.includes(tool)) continue;
        spawnHook(hook, env, cwd);
      }
    },
    "tool.execute.after": async (input) => {
      const tool = String(input?.tool ?? "").toLowerCase();
      const env = baseEnv("tool.execute.after", input);
      env.OPC_TOOL = tool;
      for (const hook of HOOKS["tool.execute.after"] ?? []) {
        if (hook.matcher && hook.matcher.length && !hook.matcher.includes(tool)) continue;
        spawnHook(hook, env, cwd);
      }
    },
    "experimental.session.compacting": async (input) => {
      for (const hook of HOOKS["experimental.session.compacting"] ?? []) {
        spawnHook(hook, baseEnv("experimental.session.compacting", input), cwd);
      }
    },
    "session.idle": async (input) => {
      for (const hook of HOOKS["session.idle"] ?? []) {
        spawnHook(hook, baseEnv("session.idle", input), cwd);
      }
    },
  };
};
